name: Deno CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            DENO_DIR: .deno_cache

        steps:
            - uses: actions/checkout@v3

            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Cache Deno dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ env.DENO_DIR }}
                  key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-deno-

            - run: deno fmt --check

            - run: deno lint

            - run: deno test --allow-read --allow-write --allow-net --coverage=cov --junit-path=./junit.xml

            - run: deno coverage --lcov cov > coverage.lcov

            - name: Upload test results to Codecov
              # https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#always
              # always run this step, regardless of success or failure
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  files: ./junit.xml
                  token: ${{ secrets.CODECOV_TOKEN }}
                  name: deno-test-results

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  files: ./coverage.lcov
                  token: ${{ secrets.CODECOV_TOKEN }}
