name: Deno CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            DENO_DIR: .deno_cache

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Cache Deno dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ env.DENO_DIR }}
                  key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-deno-

            - name: Check formatting
              run: deno fmt --check

            - name: Lint code
              run: deno lint

            - name: Run tests with coverage
              run: deno test tests --allow-ffi --allow-read --allow-write --allow-env --allow-net --allow-run --allow-scripts --coverage=cov --junit-path=./junit.xml

            - name: Generate coverage report
              run: deno coverage --lcov cov > coverage.lcov

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  files: ./junit.xml
                  token: ${{ secrets.CODECOV_TOKEN }}
                  name: deno-test-results

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  files: ./coverage.lcov
                  token: ${{ secrets.CODECOV_TOKEN }}
