name: Publish to registry
on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish to npm and jsr
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.x

            - name: Publish to jsr
              run: deno publish

            - name: Build npm package
              run: deno run -A build_npm.ts $RELEASE_VERSION

            - name: Setup Node/npm
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@totallynotdavid'

            - name: Publish to npm
              run: npm publish build/ --access=public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
