name: Publish to JSR and NPM
on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish to npm and jsr
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.x

            - name: Publish to jsr
              run: deno publish

            - run: deno run -A build_npm.ts $RELEASE_VERSION

            - uses: actions/setup-node@v3
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@totallynotdavid'

            - name: Publish to npm
              run: npm publish build/ --access=public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
